#!/bin/bash

# Convert hex colour to RGB
hex_to_rgb() {
	local hex="${1/#\#}" # Remove leading #

	if [[ ${#hex} -eq 6 ]]; then
		R=$((16#${hex:0:2}))	
		G=$((16#${hex:2:2}))	
		B=$((16#${hex:4:2}))	
		echo "Converted #${hex} to RGB(${R},${G},${B})"
	fi
}

# Check if the user provided an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <path_to_image>"
    exit 1
fi

IMAGE="$1"


# Run the wal command
wal -i "$IMAGE" -n

# Source new pywal colours
source "${HOME}/.cache/wal/colors.sh"

# Run the swww command
swww img "$IMAGE" -t wipe --transition-fps=144
echo "Wallpaper has been set."

# # Update discord and Chromium browsers
# ~/pywalGits/ChromiumPywal/generate-theme.sh
# pywal-discord -t default
# echo "Refreshed Browser and Discord."

# Update mako notifications
~/.config/mako/update-theme.sh
echo "Updated notification colourscheme."

# # Update swaync notifications
# swaync-client --reload-config
# swaync-client -rs
# echo "Updated notification colourscheme."

# Update swaylock colourscheme
~/.config/swaylock/update-theme.sh
echo "Update swaylock colourscheme."

# Refresh waybar
swaymsg reload

# Restart emacs daemon
# if [ $(systemctl --user is-active emacs.service) == "active" ]; then
#     echo "Emacsclient is running, reloading configuration."
#     emacsclient --eval '(doom/reload)' > /dev/null 2>&1
# else
#      echo "Emacs daemon is not running, skipping reload."
# fi

# Reload Spicetify (Spotify)
# This crashed spotify if open. Need to use spicetify watch -s instead but spotify pid is being a bitch
# spicetify apply

# Change Desk light
# hex_to_rgb "$color3"
# hctl on adam_s_desk --color ${R},${G},${B} --transition 3
# sleep 0.2
# hctl on hctl_used
# echo "Changed Desk Light colour"

# Notify the user
notify-send "Colour Scheme Changed" "Wallpaper has been changed to $(basename $IMAGE)!"

# Copy currently set wallpaper to Pictures folder.
# Used by hyprlock and rofi
# ln -sf "$(sed 's/%$//' ~/.cache/wal/wal)" ~/Pictures/wal.png

echo "Done"